### ISSUE TITLE
Border color to fill the border cover

### ISSUE THREAD

**Issue by zmonx** [devmuaz/coupon_uikit#2]
When adding a border colorr of decoration properties, it does not  expected because the border color is not full. 😅

![suggest](https://user-images.githubusercontent.com/47513113/205805260-e05f03df-0c39-4671-9416-ebe10042e469.png)

 `  child: CouponCard(
        curveAxis: Axis.vertical,
        borderRadius: 8,
        backgroundColor: BaseColors.primaryColor100,
        decoration: BoxDecoration(
            borderRadius: const BorderRadius.all(Radius.circular(8)),
            color: BaseColors.primaryColor100,
            border: Border.all(color: BaseColors.primaryColor)),
        firstChild: Padding(
          padding: const EdgeInsets.only(left: 10.0),
          child: Image.asset("assets/image/coupon.png"),
        ),
        secondChild: Container()......`

**Comment by devmuaz** [comment]
Hi @zmonx
I'm sorry for being too late to fix this issue, now this issue has been fixed in v0.2.0 ([d9f5481](https://github.com/devmuaz/coupon_uikit/commit/d9f5481d7e5847e2cbee15cddf11eb41f7f5e257))

I hope it solve your problem

**Comment by zmonx** [comment]
Thank you very much sir 🙏🙏

เมื่อ อา. 15 ม.ค. 2566 เวลา 21:04 AbdulMuaz Aqeel ***@***.***>
เขียนว่า:
